version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: unless-stopped
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
